### ISSUE TITLE
Push newest version to pypi.

### ISSUE THREAD

**Issue by pawisoon** [fle/django-jsignature#15]
Is there any chance to support Django 2.2.1 and Python 3.4? 
There's no other projects like this out there. 
```
  File "/Users/pawisoon/PycharmProjects/GSMPanel/venv/lib/python3.6/site-packages/django/forms/boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
TypeError: render() got an unexpected keyword argument 'renderer'
[21/Nov/2019 09:18:03] "GET /panel/mtn/edit/83/ HTTP/1.1" 500 59
```

after removing ``` renderer=self.form.renderer,``` it renders signature properly. 
So it means #11  does not work in Django 2.2.1

**Comment by pawisoon** [comment]
Ok I just realized what is going on. The owner of the repo did not push version containing #11 to pypi. Thus, when you install it by pip install django-jsignature it will be throwing you error that I posted above. To make it work you will need to install it manually or wait for newest version to appear on pypi.

**Comment by adremides** [comment]
I created a project based on the changes suggested in the last issues and PRs here. I called it [django-jsignature3](https://gitlab.com/adremides/django_jsignature3) (because it will be Django 3 compatible) and tryied to delete deprecated code too.
Feel free to make any suggestion, PR, or anything. I will try to mantain it there.

**Comment by SebCorbin** [comment]
I took over maintainership, so it should be ok now
